// Live API is the default. Enable mocks only with VITE_USE_MOCK=true or ?mock=1.
const queryMock = new URLSearchParams(window.location.search).get('mock') === '1'
export const USE_MOCK = queryMock || import.meta.env.VITE_USE_MOCK === 'true'
const BASE = import.meta.env.VITE_API_URL || 'http://localhost:8000/api'
const delay = (v) => new Promise(r => setTimeout(() => r(v), 450 + Math.random() * 400))
const questions = [
 ['React', 'Which hook stores component state?', ['useMemo','useState','useRef','useEffect'], 1], ['React', 'What does JSX compile to?', ['CSS','JavaScript calls','HTML','JSON'], 1], ['JavaScript', 'Which creates a block-scoped variable?', ['var','let','function','this'], 1], ['TypeScript', 'Why use TypeScript?', ['Runtime speed','Static type checks','Database access','Styling'], 1], ['CSS', 'Which layout is best for two dimensions?', ['Flexbox','Grid','Float','Inline'], 1], ['React', 'What key helps React track list items?', ['id prop','key prop','className','index only'], 1], ['JavaScript', 'What does async return?', ['Number','Promise','Array','Boolean'], 1], ['Git', 'Which command creates a branch?', ['git add','git branch','git push','git log'], 1], ['REST APIs', 'A successful creation usually returns?', ['200','201','404','500'], 1], ['React', 'What is a controlled input?', ['DOM-managed','State-managed','Read-only','A CSS input'], 1]
].map(([skill, question, options, answer_index], i) => ({ id: `q${i + 1}`, skill, question, options, answer_index }))
const roundCalls = { technical: 0, hr: 0 }
const mock = {
 parse: () => delay({ name:'Aarav Sharma', skills:['React','JavaScript','HTML','CSS','Git','REST APIs'], missing_skills:['TypeScript','Testing','System Design','Docker'], match_score:72 }),
 generate: () => delay({ questions }),
 submit: ({answers, questions: qs}) => { const score = Math.round(answers.filter(a => qs.find(q=>q.id===a.id)?.answer_index===a.selected).length / qs.length * 100); return delay({ score, per_skill:{ React:80, JavaScript:70, TypeScript:45, CSS:75, 'REST APIs':65 } }) },
 next: ({type}) => { const n=roundCalls[type]++; const tech=['Walk me through how React reconciliation improves rendering performance.','How would you structure state for a multi-step checkout?','Explain the difference between debounce and throttle.','How do you diagnose a slow API-backed page?','Design an error-handling strategy for a frontend app.']; const hr=['Tell me about a time you learned a difficult skill quickly.','How do you handle feedback on your work?','Describe a time you worked through a conflict with a teammate.','What kind of team environment helps you thrive?','Why does this role appeal to you?']; const set=type==='technical'?tech:hr; return delay({ reply:set[Math.min(n,set.length-1)], done:n>=5 }) },
 score: () => delay({ technical:76, hr:84, soft_skills:81, feedback:'You communicate clearly and show strong practical reasoning. Strengthen TypeScript depth and system-design vocabulary before interviews.' }),
 readiness: ({match_score,test_score,interview,missing_skills}) => delay({ readiness_score:Math.round(match_score*.35+test_score*.3+((interview.technical+interview.hr+interview.soft_skills)/3)*.35), skill_gaps:missing_skills.map((skill,i)=>({skill,level:[75,64,58,42][i]||50})), learning_path:[{step:'Strengthen TypeScript foundations',resource:'TypeScript Handbook — Everyday Types'},{step:'Build a tested React feature',resource:'React Testing Library tutorial'},{step:'Practice scalable UI architecture',resource:'Frontend system design checklist'}] })
}
async function request(path, opts={}) { const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),60000); try { const r=await fetch(`${BASE}${path}`, { ...opts, signal:controller.signal, headers:{'Content-Type':'application/json',...(opts.headers||{})} }); if(!r.ok) throw new Error((await r.text()) || 'Request failed'); return await r.json() } catch(e) { if(e.name==='AbortError') throw new Error('This is taking longer than expected. Please try again.'); if(!navigator.onLine) throw new Error('You appear to be offline. Check your connection and try again.'); throw new Error(e.message || 'We couldn’t complete that request. Please try again.') } finally { clearTimeout(timer) } }
async function upload(path, form) { const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),60000); try { const r=await fetch(`${BASE}${path}`,{method:'POST',body:form,signal:controller.signal}); if(!r.ok) throw new Error((await r.text())||'Request failed'); return await r.json() } catch(e) { if(e.name==='AbortError') throw new Error('Resume analysis timed out. Please try again.'); if(!navigator.onLine) throw new Error('You appear to be offline. Check your connection and try again.'); throw new Error(e.message || 'We couldn’t analyze your resume. Please try again.') } finally { clearTimeout(timer) } }
export const api = {
 parse: (file,target_role) => { if(USE_MOCK) return mock.parse(); const form=new FormData(); form.append('file',file); form.append('target_role',target_role); return upload('/resume/parse',form) },
 generate: (skills) => USE_MOCK ? mock.generate() : request('/test/generate',{method:'POST',body:JSON.stringify({skills})}),
 submit: (answers, questions) => USE_MOCK ? mock.submit({answers,questions}) : request('/test/submit',{method:'POST',body:JSON.stringify({answers,questions})}),
 next: (type,target_role,history) => USE_MOCK ? mock.next({type,history}) : request('/interview/next',{method:'POST',body:JSON.stringify({type,target_role,history})}),
 scoreInterview: (history,target_role) => USE_MOCK ? mock.score() : request('/interview/score',{method:'POST',body:JSON.stringify({history,target_role})}),
 readiness: (data) => USE_MOCK ? mock.readiness(data) : request('/readiness',{method:'POST',body:JSON.stringify(data)})
}
