import { useEffect, useMemo, useState } from 'react'
import { NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { Activity, ArrowDownUp, ArrowRight, BriefcaseBusiness, Building2, Check, ChevronDown, CircleHelp, Command, Download, GraduationCap, Layers3, Plus, Search, SlidersHorizontal, Sparkles, Users, X } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { getBatchGaps, getCandidates, getJobs, postJob, USE_MOCK } from './api'

const initials = name => name.split(' ').map(part => part[0]).slice(0, 2).join('').toUpperCase()
const colors = ['#1ebaa5','#3687f5','#8865ee','#ef9d4e','#e46b83']
function App() {
  const [jobs, setJobs] = useState([]), [selectedJob, setSelectedJob] = useState(''), [candidates, setCandidates] = useState([]), [gaps, setGaps] = useState([])
  const [loadingJobs, setLoadingJobs] = useState(true), [loadingCandidates, setLoadingCandidates] = useState(false), [loadingGaps, setLoadingGaps] = useState(true)
  const [jobError, setJobError] = useState(''), [candidateError, setCandidateError] = useState(''), [gapError, setGapError] = useState('')
  const [shortlisted, setShortlisted] = useState(() => new Set()), [activeCandidate, setActiveCandidate] = useState(null), [showPost, setShowPost] = useState(false)
  const [search, setSearch] = useState(''), [minScore, setMinScore] = useState(0), [sort, setSort] = useState('match_score')
  const location = useLocation(), navigate = useNavigate(), isAcademia = location.pathname.startsWith('/academia')

  const loadJobs = () => { setLoadingJobs(true); setJobError(''); getJobs().then(data => { setJobs(data); setSelectedJob(current => current || data[0]?.id || '') }).catch(error => { setJobError(error.message); setLoadingJobs(false) }).finally(() => setLoadingJobs(false)) }
  const loadCandidates = () => { if (!selectedJob) return; setLoadingCandidates(true); setCandidateError(''); getCandidates(selectedJob).then(setCandidates).catch(error => { setCandidateError(error.message); setLoadingCandidates(false) }).finally(() => setLoadingCandidates(false)) }
  const loadGaps = () => { setLoadingGaps(true); setGapError(''); getBatchGaps().then(setGaps).catch(error => { setGapError(error.message); setLoadingGaps(false) }).finally(() => setLoadingGaps(false)) }
  useEffect(() => { loadJobs() }, [])
  useEffect(() => { if (selectedJob) loadCandidates() }, [selectedJob])
  useEffect(() => { loadGaps() }, [])
  const job = jobs.find(item => item.id === selectedJob)
  const filtered = useMemo(() => candidates.filter(person => person.name.toLowerCase().includes(search.toLowerCase()) && person.match_score >= minScore).sort((a,b) => b[sort] - a[sort]), [candidates, search, minScore, sort])
  const average = candidates.length ? Math.round(candidates.reduce((sum, person) => sum + person.readiness_score, 0) / candidates.length) : 0
  const workshops = gaps.slice(0, 3).map((gap, index) => ({ ...gap, duration: ['2-day sprint', '1-week lab', '3-session workshop'][index], icon: ['⌘', '◉', '↗'][index], description: [`Design scalable systems with hands-on architecture challenges.`, `Practice clear storytelling, feedback, and confident communication.`, `Build and deploy a cloud-ready project from scratch.`][index] }))

  async function createRole(payload) {
    const created = await postJob(payload)
    setJobs(current => [created, ...current.filter(item => item.id !== created.id)])
    setSelectedJob(created.id)
    setShowPost(false)
    navigate('/')
  }
  const toggleShortlist = id => setShortlisted(old => { const next = new Set(old); next.has(id) ? next.delete(id) : next.add(id); return next })

  return <div className="app-shell">
    <aside className="sidebar">
      <a className="brand" href="/" onClick={e => { e.preventDefault(); navigate('/') }}><span className="brand-mark"><Layers3 size={19}/></span><span>SkillBridge<span className="brand-dot">.</span></span></a>
      <div className="workspace-label">WORKSPACE</div>
      <div className="switch-label">YOUR VIEWS</div>
      <nav className="view-nav">
        <a className="nav-item" href="http://localhost:5173"><Building2 size={18}/><span>Student app</span><span className="nav-dot"/></a>
        <NavLink to="/" end className={({isActive}) => `nav-item ${isActive ? 'active' : ''}`}><Building2 size={18}/><span>Industry</span><span className="nav-dot"/></NavLink>
        <NavLink to="/academia" className={({isActive}) => `nav-item ${isActive ? 'active' : ''}`}><GraduationCap size={18}/><span>Academia</span><span className="nav-dot"/></NavLink>
      </nav>
      <div className="sidebar-bottom"><div className="help-card"><div className="help-icon"><CircleHelp size={17}/></div><strong>Need a hand?</strong><span>Explore the SkillBridge guide</span><button onClick={() => window.open('https://github.com/Anirudhh-Srinivasan/SkillBridge', '_blank')}>Open help center <ArrowRight size={14}/></button></div><div className="user-profile"><div className="avatar avatar-purple">AS</div><div className="user-copy"><strong>Admin workspace</strong><span>SRM Institute of Science</span></div><ChevronDown size={16}/></div></div>
    </aside>
    <main className="main-area">
      <header className="topbar"><div className="breadcrumbs"><span>SkillBridge</span><span className="crumb-slash">/</span><strong>{isAcademia ? 'Academia' : 'Industry'}</strong></div><div className="top-actions"><a href="http://localhost:5173">Student app ↗</a><span className={`live-pill ${USE_MOCK ? 'mock' : ''}`}><i/>{USE_MOCK ? 'Demo data' : 'Live data'}</span><div className="top-avatar">AS</div></div></header>
      <Routes>
        <Route path="/" element={<IndustryPage {...{jobs,job,selectedJob,setSelectedJob,candidates,filtered,average,shortlisted,activeCandidate,setActiveCandidate,loadingJobs,loadingCandidates,jobError,candidateError,search,setSearch,minScore,setMinScore,sort,setSort,setShowPost,toggleShortlist,retryJobs:loadJobs,retryCandidates:loadCandidates}}/>}/>
        <Route path="/academia" element={<AcademiaPage {...{jobs,candidates,gaps,loadingJobs,loadingCandidates,loadingGaps,jobError,gapError,workshops,average,retryJobs:loadJobs,retryGaps:loadGaps}}/>}/>
        <Route path="*" element={<IndustryPage {...{jobs,job,selectedJob,setSelectedJob,candidates,filtered,average,shortlisted,activeCandidate,setActiveCandidate,loadingJobs,loadingCandidates,jobError,candidateError,search,setSearch,minScore,setMinScore,sort,setSort,setShowPost,toggleShortlist,retryJobs:loadJobs,retryCandidates:loadCandidates}}/>}/>
      </Routes>
      <footer className="footer"><span>© 2025 SkillBridge</span><span>Verified skills, not just resumes <span className="footer-heart">✦</span></span><span className="version">PORTAL V1.0</span></footer>
    </main>
    {activeCandidate && <CandidateDrawer candidate={activeCandidate} job={job} shortlist={shortlisted.has(activeCandidate.id)} onToggle={() => toggleShortlist(activeCandidate.id)} onClose={() => setActiveCandidate(null)}/>}
    {showPost && <PostJobModal onClose={() => setShowPost(false)} onSubmit={createRole}/>}
  </div>
}

function IndustryPage(p) {
  const [view, setView] = useState('Candidates')
  return <div className="page-wrap">
    <div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line"/> TALENT INTELLIGENCE</div><h1>Industry <span className="heading-accent">overview</span></h1><p>Find, evaluate, and connect with career-ready talent.</p></div><button className="button-primary" onClick={() => p.setShowPost(true)}><Plus size={17}/> Post a new role</button></div>
    <div className="stat-grid">
      <StatCard label="TOTAL CANDIDATES" value={p.loadingCandidates ? '—' : String(p.candidates.length).padStart(2,'0')} trend="Across your talent pool" icon={<Users size={18}/>} tone="teal"/>
      <StatCard label="AVG. READINESS SCORE" value={p.loadingCandidates ? '—' : `${p.average}%`} trend="Candidate readiness index" icon={<Activity size={18}/>} tone="blue"/>
      <StatCard label="SHORTLISTED" value={String(p.shortlisted.size).padStart(2,'0')} trend="Saved for your team" icon={<Check size={18}/>} tone="purple"/>
    </div>
    <div className="content-grid">
      <section className="card jobs-card"><div className="section-top"><div><div className="section-eyebrow">OPEN OPPORTUNITIES</div><h2>Active roles <span className="count-badge">{p.jobs.length}</span></h2></div><button className="icon-button" aria-label="Add role" onClick={() => p.setShowPost(true)}><Plus size={17}/></button></div>
        {p.loadingJobs ? <LoadingRows count={4}/> : p.jobError ? <InlineError message={p.jobError} onRetry={p.retryJobs}/> : p.jobs.length === 0 ? <EmptyState title="No roles yet" body="Post your first role to start matching with students."/> : <div className="job-list">{p.jobs.map((item,index) => <button key={item.id} onClick={() => p.setSelectedJob(item.id)} className={`job-row ${p.selectedJob === item.id ? 'selected' : ''}`}><span className="company-icon" style={{'--job-color':colors[index%colors.length]}}>{item.company.slice(0,1)}</span><span className="job-copy"><strong>{item.role}</strong><span>{item.company} <i>·</i> {item.required_skills.length} skills</span></span><span className="job-chevron"><ArrowRight size={15}/></span></button>)}</div>}
        <button className="text-link full-width" onClick={() => p.setShowPost(true)}><Plus size={15}/> Add another role</button>
      </section>
      <section className="card candidates-card"><div className="section-top candidate-header"><div><div className="section-eyebrow">ROLE MATCHING</div><h2>{p.job ? p.job.role : 'Candidate matches'}</h2><p className="section-subtitle">{p.job ? `${p.job.company} · ranked by role fit` : 'Select a role to see ranked candidates'}</p></div><button className="export-button" onClick={() => downloadCsv(p.filtered)}><Download size={15}/> Export</button></div>
        <div className="candidate-controls"><div className="segmented"><button className={view === 'Candidates' ? 'chosen' : ''} onClick={() => setView('Candidates')}>Candidates <span>{p.filtered.length}</span></button><button className={view === 'Shortlisted' ? 'chosen' : ''} onClick={() => setView('Shortlisted')}>Shortlisted <span>{p.shortlisted.size}</span></button></div><div className="search-box"><Search size={15}/><input placeholder="Search candidates..." value={p.search} onChange={e=>p.setSearch(e.target.value)}/><span className="shortcut">⌘ K</span></div></div>
        <div className="filter-strip"><div className="filter-label"><SlidersHorizontal size={14}/> Match score <strong>{p.minScore}%+</strong></div><input className="range-slider" aria-label="Minimum match score" type="range" min="0" max="100" step="5" value={p.minScore} onChange={e=>p.setMinScore(Number(e.target.value))}/><span className="filter-spacer"/><span className="sort-label">Sort by</span><select value={p.sort} onChange={e=>p.setSort(e.target.value)}><option value="match_score">Best match</option><option value="readiness_score">Readiness</option></select><ArrowDownUp size={14} className="sort-icon"/></div>
        <div className="table-wrap"><table className="candidate-table"><thead><tr><th>CANDIDATE</th><th>SKILLS MATCHED</th><th>MATCH SCORE</th><th>READINESS</th><th/></tr></thead><tbody>
          {p.loadingCandidates ? <tr><td colSpan="5"><div className="table-loading"><span className="spinner"/>Finding your best matches...</div></td></tr> : p.candidateError ? <tr><td colSpan="5"><InlineError message={p.candidateError} onRetry={p.retryCandidates}/></td></tr> : (view === 'Shortlisted' ? p.filtered.filter(item=>p.shortlisted.has(item.id)) : p.filtered).map((person,index)=><CandidateRow key={person.id} person={person} job={p.job} rank={index+1} onClick={()=>p.setActiveCandidate(person)}/>)}
          {!p.loadingCandidates && !p.candidateError && (view === 'Shortlisted' ? p.filtered.filter(item=>p.shortlisted.has(item.id)) : p.filtered).length===0 && <tr><td colSpan="5"><EmptyState title={view==='Shortlisted'?'No shortlisted candidates':'No matching candidates'} body={view==='Shortlisted'?'Save a candidate to find them here.':'Try lowering the minimum score or changing your search.'}/></td></tr>}
        </tbody></table></div>
        <div className="table-footer"><span>Showing <strong>{p.loadingCandidates?0:(view==='Shortlisted'?p.filtered.filter(item=>p.shortlisted.has(item.id)):p.filtered).length}</strong> candidates</span><span className="table-footer-note"><span className="legend-dot"/> AI skill match · updated just now</span></div>
      </section>
    </div>
    <div className="trust-banner"><div className="trust-icon"><Sparkles size={18}/></div><div><strong>Better matches start with verified skills.</strong><span>Every candidate score is backed by skill assessments and interview signals.</span></div><button onClick={()=>{}}>How scoring works <ArrowRight size={14}/></button><div className="banner-orb orb-one"/><div className="banner-orb orb-two"/></div>
  </div>
}

function AcademiaPage(p) {
  const [allCandidates,setAllCandidates] = useState([]), [allLoading,setAllLoading] = useState(true), [allError,setAllError] = useState('')
  const loadAllCandidates=()=>{setAllLoading(true);setAllError('');if(!p.jobs.length){setAllLoading(false);return}Promise.all(p.jobs.map(job=>getCandidates(job.id))).then(groups=>{const unique=new Map();groups.flat().forEach(person=>unique.set(person.id,person));setAllCandidates([...unique.values()])}).catch(e=>{setAllError(e.message);setAllLoading(false)}).finally(()=>setAllLoading(false))}
  useEffect(()=>{if(p.jobs.length)loadAllCandidates()},[p.jobs])
  const histogram=useMemo(()=>{const bins=[['0–39',0],['40–54',0],['55–69',0],['70–84',0],['85–100',0]];allCandidates.forEach(item=>{const s=item.readiness_score, i=s<40?0:s<55?1:s<70?2:s<85?3:4;bins[i][1]++});return bins.map(([range,count])=>({range,count}))},[allCandidates])
  const top3=new Set(p.gaps.slice(0,3).map(item=>item.skill))
  return <div className="page-wrap academia-page">
    <div className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line"/> ACADEMIC INSIGHTS</div><h1>Academia <span className="heading-accent">overview</span></h1><p>Turn skill signals into stronger learning outcomes.</p></div><div className="updated-chip"><span/> Cohort data · 2024–25</div></div>
    <div className="stat-grid academia-stats"><StatCard label="STUDENTS ANALYZED" value={allLoading?'—':String(allCandidates.length).padStart(2,'0')} trend="Across active role pathways" icon={<GraduationCap size={18}/>} tone="teal"/><StatCard label="COHORT READINESS" value={allLoading?'—':`${Math.round(allCandidates.reduce((n,c)=>n+c.readiness_score,0)/(allCandidates.length||1))}%`} trend="Average readiness score" icon={<Activity size={18}/>} tone="blue"/><StatCard label="SKILL GAPS TRACKED" value={p.loadingGaps?'—':String(p.gaps.length).padStart(2,'0')} trend="Across the current cohort" icon={<Layers3 size={18}/>} tone="purple"/></div>
    <div className="academic-grid">
      <section className="card gap-card"><div className="section-top"><div><div className="section-eyebrow">COHORT SKILL INTELLIGENCE</div><h2>Where students need support</h2><p className="section-subtitle">Share of students who need to strengthen each skill</p></div><button className="period-select">Current cohort <ChevronDown size={14}/></button></div>
        {p.loadingGaps?<ChartLoading/>:p.gapError?<InlineError message={p.gapError} onRetry={p.retryGaps}/>:p.gaps.length===0?<EmptyState title="No skill gap data" body="Batch insights will appear once assessments are available."/>:<><div className="gap-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={p.gaps} layout="vertical" margin={{top:4,right:36,left:4,bottom:0}} barCategoryGap={14}><CartesianGrid horizontal={false} stroke="#edf1f5"/><XAxis type="number" domain={[0,100]} tickLine={false} axisLine={false} tick={{fill:'#97a3b3',fontSize:11}} tickFormatter={v=>`${v}%`}/><YAxis type="category" dataKey="skill" width={132} tickLine={false} axisLine={false} tick={{fill:'#5e6d80',fontSize:12}}/><Tooltip cursor={{fill:'#f7f9fb'}} formatter={value=>[`${value}% need support`,'Skill gap']} contentStyle={{borderRadius:12,border:'1px solid #e8edf2',fontSize:12}}/><Bar dataKey="gap_percent" radius={[0,5,5,0]} barSize={15} label={{position:'right',formatter:v=>`${v}%`,fill:'#627184',fontSize:11}}>{p.gaps.map((item,index)=><Cell key={item.skill} fill={index<3?'#e56f76':'#38b6a7'}/>)}</Bar></BarChart></ResponsiveContainer></div><div className="chart-legend"><span><i className="red-dot"/> Priority gap · top 3</span><span><i className="teal-dot"/> Developing opportunity</span></div></>}
      </section>
      <section className="card workshop-card"><div className="section-top"><div><div className="section-eyebrow">TAKE ACTION</div><h2>Recommended workshops</h2><p className="section-subtitle">Built around your cohort’s biggest gaps</p></div><span className="sparkle-chip"><Sparkles size={14}/></span></div>
        {p.loadingGaps?<LoadingRows count={3}/>:p.gapError?<InlineError message={p.gapError} onRetry={p.retryGaps}/>:workshopsEmpty(p.workshops)?<EmptyState title="No recommendations yet" body="Workshop ideas appear when skill gaps are reported."/>:<div className="workshop-list">{p.workshops.map((item,index)=><div className="workshop-item" key={item.skill}><div className={`workshop-symbol symbol-${index}`}>{item.icon}</div><div className="workshop-copy"><div className="workshop-kicker">{item.duration} <span>·</span> {item.gap_percent}% cohort gap</div><strong>{item.skill} essentials</strong><p>{item.description}</p></div><ArrowRight size={16} className="workshop-arrow"/></div>)}</div>}
      </section>
    </div>
    <section className="card distribution-card"><div className="section-top"><div><div className="section-eyebrow">PLACEMENT READINESS</div><h2>Readiness score distribution</h2><p className="section-subtitle">How your cohort is progressing toward placement-ready</p></div><span className="cohort-count"><Users size={15}/>{allLoading?'—':allCandidates.length} students</span></div>
      {allLoading?<ChartLoading/>:allError?<InlineError message={allError} onRetry={loadAllCandidates}/>:allCandidates.length===0?<EmptyState title="No candidate scores yet" body="Readiness scores will appear here when candidates are assessed."/>:<div className="histogram"><ResponsiveContainer width="100%" height="100%"><BarChart data={histogram} margin={{top:18,right:12,left:0,bottom:0}} barCategoryGap="24%"><CartesianGrid vertical={false} stroke="#edf1f5"/><XAxis dataKey="range" tickLine={false} axisLine={false} tick={{fill:'#738197',fontSize:12}} tickFormatter={v=>`${v} score`}/><YAxis allowDecimals={false} tickLine={false} axisLine={false} tick={{fill:'#9aa5b4',fontSize:11}}/><Tooltip formatter={value=>[`${value} students`,'Cohort']} contentStyle={{borderRadius:12,border:'1px solid #e8edf2',fontSize:12}}/><Bar dataKey="count" fill="#2bb6a4" radius={[6,6,0,0]} maxBarSize={58} label={{position:'top',fill:'#57677a',fontSize:12}}/></BarChart></ResponsiveContainer></div>}
      <div className="distribution-legend"><span><i/> Students</span><span>Readiness score band</span></div>
    </section>
  </div>
}
const workshopsEmpty = list => list.length === 0

function StatCard({label,value,trend,icon,tone}) { return <div className="stat-card"><div className="stat-meta"><span>{label}</span><span className={`stat-icon ${tone}`}>{icon}</span></div><div className="stat-value">{value}</div><div className="stat-trend"><span className="trend-line">↗</span>{trend}</div><span className="stat-watermark">{icon}</span></div> }
function CandidateRow({person,job,rank,onClick}) { const skills=job?.required_skills||[]; return <tr className="candidate-row" onClick={onClick}><td><div className="candidate-name"><div className={`avatar avatar-${rank%4}`}>{initials(person.name)}</div><div><strong>{person.name}</strong><span>Candidate · {person.id}</span></div></div></td><td><div className="skill-chips">{person.skills.filter(skill=>skills.includes(skill)).slice(0,3).map(skill=><span className="skill-chip matched" key={skill}><i/>{skill}</span>)}{person.skills.filter(skill=>!skills.includes(skill)).slice(0,1).map(skill=><span className="skill-chip" key={skill}>{skill}</span>)}{!person.skills.some(skill=>skills.includes(skill))&&<span className="skill-chip">Related skills</span>}</div></td><td><div className="score-cell"><div className="score-top"><strong>{person.match_score}%</strong><span>match</span></div><div className="score-track"><i style={{width:`${person.match_score}%`}}/></div></div></td><td><span className={`readiness-badge ${person.readiness_score>=85?'ready':person.readiness_score>=70?'near':'developing'}`}>{person.readiness_score}%</span></td><td><ArrowRight size={15} className="row-arrow"/></td></tr> }
function CandidateDrawer({candidate,job,shortlist,onToggle,onClose}) { const matches=(job?.required_skills||[]).filter(skill=>candidate.skills.includes(skill)), gaps=(job?.required_skills||[]).filter(skill=>!candidate.skills.includes(skill)); return <><button className="drawer-scrim" aria-label="Close candidate details" onClick={onClose}/><aside className="drawer"><div className="drawer-head"><span className="section-eyebrow">CANDIDATE PROFILE</span><button className="icon-button" onClick={onClose}><X size={18}/></button></div><div className="profile-block"><div className="avatar avatar-large avatar-purple">{initials(candidate.name)}</div><h2>{candidate.name}</h2><p>Student candidate <span>·</span> SRM Institute</p><div className="profile-scores"><div><strong>{candidate.match_score}%</strong><span>Role match</span></div><div><strong>{candidate.readiness_score}%</strong><span>Readiness</span></div></div></div><div className="drawer-section"><div className="drawer-section-title">ROLE SKILL ALIGNMENT <span>{matches.length}/{job?.required_skills.length||0}</span></div><div className="drawer-skill-list">{matches.map(skill=><span key={skill} className="drawer-skill good"><Check size={14}/>{skill}</span>)}{gaps.map(skill=><span key={skill} className="drawer-skill missing"><span>+</span>{skill}</span>)}</div></div><div className="drawer-section"><div className="drawer-section-title">VERIFIED SKILLS</div><div className="verified-skills">{candidate.skills.map(skill=><span key={skill}>{skill}</span>)}</div></div><div className="drawer-note"><Sparkles size={17}/><p>Skill match is calculated against the requirements for <strong>{job?.role||'this role'}</strong>.</p></div><div className="drawer-actions"><button className={`button-primary ${shortlist?'button-saved':''}`} onClick={onToggle}>{shortlist?<><Check size={17}/> Shortlisted</>:<><Plus size={17}/> Add to shortlist</>}</button><button className="button-secondary" onClick={onClose}>Close profile</button></div></aside></> }
function PostJobModal({onClose,onSubmit}) { const [company,setCompany]=useState(''),[role,setRole]=useState(''),[skills,setSkills]=useState([]),[skillInput,setSkillInput]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState(''); const addSkill=()=>{const next=skillInput.trim();if(next&&!skills.some(s=>s.toLowerCase()===next.toLowerCase()))setSkills([...skills,next]);setSkillInput('')}; async function submit(e){e.preventDefault();if(!company.trim()||!role.trim()||!skills.length){setError('Add a company, role, and at least one required skill.');return}setSaving(true);setError('');try{await onSubmit({company:company.trim(),role:role.trim(),required_skills:skills})}catch(e){setError(e.message)}finally{setSaving(false)}} return <div className="modal-scrim" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="modal" onSubmit={submit}><div className="modal-header"><div><span className="section-eyebrow">GROW YOUR TALENT PIPELINE</span><h2>Post a new role</h2><p>We’ll match your requirements with verified student skills.</p></div><button type="button" className="icon-button" onClick={onClose}><X size={18}/></button></div><label className="field-label">Company name<input autoFocus value={company} onChange={e=>setCompany(e.target.value)} placeholder="e.g. Acme Technologies"/></label><label className="field-label">Role title<input value={role} onChange={e=>setRole(e.target.value)} placeholder="e.g. Software Engineer"/></label><div className="field-label">Required skills<div className="skill-entry"><input value={skillInput} onChange={e=>setSkillInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addSkill()}}} placeholder="Type a skill and press Enter"/><button type="button" className="button-secondary small" onClick={addSkill}><Plus size={14}/> Add</button></div><div className="modal-tags">{skills.map(skill=><button type="button" className="modal-tag" key={skill} onClick={()=>setSkills(skills.filter(s=>s!==skill))}>{skill}<X size={12}/></button>)}</div></div>{error&&<div className="form-error">{error}<button type="button" className="button-secondary small" onClick={e=>e.currentTarget.closest('form').requestSubmit()}>Retry</button></div>}<div className="modal-actions"><button type="button" className="button-secondary" onClick={onClose}>Cancel</button><button className="button-primary" disabled={saving}>{saving?<><span className="button-spinner"/> Posting...</>:<><Plus size={16}/> Post role</>}</button></div></form></div> }
function LoadingRows({count=3}) { return <div className="loading-rows">{Array.from({length:count},(_,i)=><div className="loading-row" key={i}><span className="skeleton circle"/><span className="skeleton long"/><span className="skeleton short"/></div>)}</div> }
function ChartLoading() { return <div className="chart-loading"><span className="spinner"/><span>Loading cohort insights…</span></div> }
function InlineError({message,onRetry}) { return <div className="inline-error"><strong>We couldn’t load this data.</strong><span>{message}</span>{onRetry&&<button className="button-secondary small" onClick={onRetry}>Retry</button>}</div> }
function EmptyState({title,body}) { return <div className="empty-state"><div className="empty-icon"><Search size={18}/></div><strong>{title}</strong><span>{body}</span></div> }
function downloadCsv(data) { if(!data.length)return; const rows=[['Name','Candidate ID','Skills','Match score','Readiness score'],...data.map(p=>[p.name,p.id,p.skills.join('; '),p.match_score,p.readiness_score])];const csv=rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download='skillbridge-candidates.csv';link.click();URL.revokeObjectURL(link.href) }

export default App
